authorName: default
experimentName: rfag
trialConcurrency: 5
maxExecDuration: 24h
maxTrialNum: 300
trainingServicePlatform: local
# 搜索空间文件
searchSpacePath: _search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
# 运行的命令，以及 Trial 代码的路径
trial:
  command: python3 run.py
  codeDir: .
  gpuNum: 1
